package com.yaobanTech.springcloud.repository;

import com.yaobanTech.springcloud.domain.BizSignPoint;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface BizSignPointMapper {

    @Update({"<script>",
            "update biz_sign_point",
            "<set>",
            "<if test='signPointCode != null'>",
            "sign_point_code = #{signPointCode} ,",
            "</if>",
            "<if test='currentChoosedAddress != null'>",
            "current_choosed_address = #{currentChoosedAddress} ,",
            "</if>",
            "<if test='troubleCode != null'>",
            "trouble_code = #{troubleCode} ,",
            "</if>",
            "<if test='troubleReason != null'>",
            "trouble_reason = #{troubleReason} ,",
            "</if>",
            "<if test='hiddenDangerType != null'>",
            "hidden_danger_type = #{hiddenDangerType} ,",
            "</if>",
            "<if test='handleSuggestion != null'>",
            "handle_suggestion = #{handleSuggestion} ,",
            "</if>",
            "<if test='location != null'>",
            "location = #{location} ,",
            "</if>",
            "<if test='pipeDiameter != null'>",
            "pipe_diameter = #{pipeDiameter} ,",
            "</if>",
            "<if test='memo != null'>",
            "memo = #{memo},",
            "</if>",
            "<if test='siteConditions != null'>",
            "site_conditions = #{siteConditions} ,",
            "</if>",
            "<if test='siteConditionsDesc != null'>",
            "site_conditions_desc = #{siteConditionsDesc} ," ,
            "</if>",
            "<if test='hiddenDangerAddress != null'>",
            "hidden_danger_address = #{hiddenDangerAddress} ," ,
            "</if>",
            "<if test='hiddenDangerReason != null'>",
            "hidden_danger_reason = #{hiddenDangerReason} ," ,
            "</if>",
            "<if test='dischargeAddress != null'>",
            "discharge_address = #{dischargeAddress} ," ,
            "</if>",
            "<if test='dischargeTimeLast != null'>",
            "discharge_time_last = #{dischargeTimeLast} ," ,
            "</if>",
            "<if test='dischargeTime != null'>",
            "discharge_time = #{dischargeTime} ," ,
            "</if>",
            "<if test='estimatedDischarge != null'>",
            "estimated_discharge = #{estimatedDischarge} ," ,
            "</if>",
            "<if test='routeType != null'>",
            "route_type = #{routeType} ," ,
            "</if>",
            "<if test='pointInspectionType != null'>",
            "point_inspection_type = #{pointInspectionType} ," ,
            "</if>",
            "<if test='signPointStatus != null'>",
            "sign_point_status = #{signPointStatus} ," ,
            "</if>",
            "<if test='modifyTime != null'>",
            "modify_time = #{modifyTime} ," ,
            "</if>",
            "</set>",
            "where id = #{id}",
            "</script>"})
    void update(BizSignPoint bizSignPoint);
}